"""Position scorers for the refinement sweep — how good was the move the LLM picked?

The sweep needs a *fixed* set of decision positions and a per-position quality score,
both independent of which candidate is being graded. :class:`PositionScorer` is that
seam:

* :meth:`PositionScorer.positions` returns a frozen, seed-determined position set.
  Freezing the set is the deterministic analogue of common-random-numbers (CLAUDE.md
  §7): every candidate is graded on identical inputs, so there is *zero* dice variance
  in the comparison.
* :meth:`PositionScorer.score` grades a chosen move (higher is better).

The default :class:`ReferenceAgentScorer` is self-contained (no gnubg): it grades
against an on-`main` reference agent — :class:`~bgrl.agents.pubeval_agent.PubevalAgent`
by default (move-agreement) or a trained value net (equity-loss). The gnubg-backed
scorer named in the WP4 plan is :class:`GnubgPositionScorer`, a documented stub wired
in only after WP3's serialization pipeline merges.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Protocol, runtime_checkable

import numpy as np

from bgrl.agents.base import Agent
from bgrl.agents.pubeval_agent import PubevalAgent
from bgrl.agents.random_agent import RandomAgent
from bgrl.agents.value_agent import ValueAgent
from bgrl.env import Dice, Env, EnvState, Move, RandomDiceSource, encode
from bgrl.game import play_game
from bgrl.nets.base import ValueNet
from bgrl.nets.equity import CENTERED_CUBE, CubeContext, equity


class ScoreMode(Enum):
    """How a chosen move is graded against the reference."""

    AGREEMENT = "agreement"  # 1.0 if the move equals the reference's choice, else 0.0
    EQUITY_LOSS = "equity_loss"  # chosen_equity - best_equity (<= 0; 0 is optimal)


@dataclass(frozen=True, slots=True)
class ScoredPosition:
    """A frozen decision position plus the reference's verdict.

    ``equities`` (mover's POV, aligned with ``legal``) is present only for value-based
    oracles and enables :data:`ScoreMode.EQUITY_LOSS`.
    """

    state: EnvState
    dice: Dice
    legal: tuple[tuple[Move, EnvState], ...]
    reference_move: Move
    equities: tuple[float, ...] | None = None


@runtime_checkable
class PositionScorer(Protocol):
    """Builds a fixed scoring set and grades chosen moves on it."""

    name: str

    def positions(self, *, n: int, seed: int) -> list[ScoredPosition]: ...

    def score(self, pos: ScoredPosition, chosen: Move) -> float: ...


class ReferenceAgentScorer:
    """Grades LLM moves against an on-``main`` reference agent over a frozen set.

    Positions are generated by random self-play (seeded), keeping only genuine choices
    (more than one legal move) and sampling one mid-game position per game, so the set
    is deterministic and free of trivial forced moves.
    """

    name = "reference_agent"

    def __init__(
        self,
        oracle: Agent,
        *,
        value_net: ValueNet | None = None,
        cube: CubeContext = CENTERED_CUBE,
        mode: ScoreMode = ScoreMode.AGREEMENT,
        min_decisions: int = 6,
    ) -> None:
        if mode is ScoreMode.EQUITY_LOSS and value_net is None:
            raise ValueError("equity-loss scoring requires a value_net")
        self._oracle = oracle
        self._value_net = value_net
        self._cube = cube
        self._mode = mode
        self._min_decisions = min_decisions

    @classmethod
    def pubeval(cls, *, min_decisions: int = 6) -> ReferenceAgentScorer:
        """Pubeval oracle, move-agreement scoring — the WP3-independent default."""
        return cls(PubevalAgent(), mode=ScoreMode.AGREEMENT, min_decisions=min_decisions)

    @classmethod
    def from_checkpoint(
        cls,
        path: str | Path,
        *,
        mode: ScoreMode = ScoreMode.EQUITY_LOSS,
        min_decisions: int = 6,
    ) -> ReferenceAgentScorer:
        """Trained value-net oracle (stronger than pubeval); enables equity-loss."""
        from bgrl.serialization.checkpoint import load_checkpoint, load_net

        net = load_net(load_checkpoint(path))
        return cls(ValueAgent(net), value_net=net, mode=mode, min_decisions=min_decisions)

    def positions(self, *, n: int, seed: int) -> list[ScoredPosition]:
        rng = np.random.default_rng(seed)
        generator = RandomAgent(rng)  # diverse positions; both seats share one agent
        out: list[ScoredPosition] = []
        game = 0
        while len(out) < n:
            dice = RandomDiceSource(np.random.default_rng([seed, game]))
            result = play_game(generator, generator, dice, record=True)
            game += 1
            decisions = [
                (step.state, step.dice, legal)
                for step in result.steps
                if len(legal := Env.legal_moves(step.state, step.dice)) > 1
            ]
            if len(decisions) < self._min_decisions:
                continue
            state, roll, legal = decisions[len(decisions) // 2]
            out.append(self._make_scored(state, roll, legal))
        return out

    def _make_scored(
        self, state: EnvState, dice: Dice, legal: list[tuple[Move, EnvState]]
    ) -> ScoredPosition:
        reference = self._oracle.act(state, dice, legal)
        equities = self._mover_equities(legal) if self._value_net is not None else None
        return ScoredPosition(state, dice, tuple(legal), reference, equities)

    def _mover_equities(self, legal: list[tuple[Move, EnvState]]) -> tuple[float, ...]:
        assert self._value_net is not None
        features = np.stack([encode(after, perspective=after.turn) for _, after in legal])
        opp_outcome = self._value_net.evaluate(features)
        mover_equity = -equity(opp_outcome, self._cube)  # flip opponent's POV to the mover's
        return tuple(float(e) for e in np.atleast_1d(mover_equity))

    def score(self, pos: ScoredPosition, chosen: Move) -> float:
        if self._mode is ScoreMode.AGREEMENT:
            return 1.0 if chosen == pos.reference_move else 0.0
        assert pos.equities is not None  # guaranteed: EQUITY_LOSS implies value_net
        best = max(pos.equities)
        for i, (move, _after) in enumerate(pos.legal):
            if move == chosen:
                return pos.equities[i] - best
        raise ValueError("chosen move is not among the scored position's legal moves")


class GnubgPositionScorer:
    """Grades against gnubg's analysis — the WP4 plan's stated default scorer.

    DEFERRED: gnubg lives in WP3's serialization pipeline, which is not on ``main``
    yet. This stub fixes the :class:`PositionScorer` shape now; the body is wired to
    WP3's gnubg batch-analysis path post-merge (see plans/wp4-llm-agent.md).
    """

    name = "gnubg"
    _MSG = "GnubgPositionScorer is wired after WP3's gnubg pipeline merges"

    def positions(self, *, n: int, seed: int) -> list[ScoredPosition]:
        raise NotImplementedError(self._MSG)

    def score(self, pos: ScoredPosition, chosen: Move) -> float:
        raise NotImplementedError(self._MSG)
